services:
  m-banking-api:
    image: "m-banking-api"
    build: .
    container_name: m-banking-api
    ports:
      - 2222:8080
    volumes:
      - D:/SpringBootCourse/file-server/:/file-server/
    networks:
      - m-banking-net
    depends_on:
      - m-banking-db

  m-banking-db:
    image: postgres:16.3-bullseye
    container_name: m-banking-db
    ports:
      - 7777:5432
    environment:
      POSTGRES_PASSWORD: sbc11@2024
      POSTGRES_USER: sbc11
      POSTGRES_DB: m_banking_db
    volumes:
      - m-banking-vol:/var/lib/postgresql/data
    networks:
      - m-banking-net

volumes:
  m-banking-vol:

networks:
  m-banking-net:

